##
# @file
#
# Travis CI script for the Brackets coding puzzle
#
# @author Emil Maskovsky
#
language: cpp
compiler:
- gcc
#- clang

before_install:
#- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#- sudo apt-get update -qq
install:
#- sudo apt-get install -qq gcc-4.8 g++-4.8
#- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script: httpServer/make
# need to install the Boost libraries to the sandbox
before_script:
- sudo apt-get update -qq
- sudo apt-get install libboost-thread-dev libboost-system-dev
notifications:
email:
recipients: ankithbti007@gmail.com
on_success: change
on_failure: always
