##
# @file
#
# Travis CI script for the Brackets coding puzzle
#
# @author Ankit Gupta
#
language: cpp
compiler:
#- gcc
- clang

before_install:
#- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get install libgtest-dev
- "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
- sudo apt-get install libboost-thread-dev libboost-system-dev

install:
#- sudo apt-get install -qq gcc-4.8 g++-4.8
#- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script: httpServer/make
# need to install the Boost libraries to the sandbox
before_script:
- pwd
- cd httpServer
- pwd
- which sh
- sudo /bin/bash init.sh

script: make -f Makefile_travis createlib ; make -f Makefile_travis all

branches:
only:
- master

notifications:
recipients:
- ankithbti007@gmail.com
email:
on_success: change
on_failure: always

rvm:
#- 9.00
